---
title: "New Manager Bounce"
subtitle: "Exploratory Analysis"
author: "Josh Muncke"
date: "21/03/2019"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploratory Analysis

```{r load our packages, message=FALSE}
library(tidyverse)
library(lubridate)
library(magrittr)
library(redbull)
library(feather)
```

## Load data

```{r load data}
game_and_manager_data <- read_feather("../data/prep/game_and_manager_data_prep.feather")
```

## Plotting setup

```{r plot setup}
theme_set(theme_rb())
source_text <- "Source: football-data.co.uk; Wikipedia"
```

## Exploratory Analysis

### Simple questions

**Average goals per game over time**
```{r gpg over time, warning=F}
game_and_manager_data %>%
  mutate(game_month = round_date(game_date, "month")) %>%
  group_by(game_month) %>%
  summarise(goals = sum(goals), games = n_distinct(game_id)) %>%
  mutate(goals_per_game = goals/games) %>%
  ggplot(aes(x = game_month, y = (goals_per_game))) +
  geom_point() + 
  geom_smooth() + 
  labs(caption = source_text)
```

**Distribution of goals per team per game**
```{r}
game_and_manager_data %>%
  ggplot(aes(x = goals, fill = game_location)) +
  geom_histogram(binwidth = 1) +
  facet_wrap(~ game_location) +
  scale_fill_redbull("bloomberg")


  mutate(game_month = round_date(game_date, "month")) %>%
  group_by(game_month) %>%
  summarise(goals = sum(goals), games = n_distinct(game_id)) %>%
  mutate(goals_per_game = goals/games) %>%
  ggplot(aes(x = game_month, y = (goals_per_game))) +
  geom_point() + 
  geom_smooth() + 
  labs(caption = source_text)
```

```{r}
home_team <- "Manchester United"
away_team <- "Liverpool"

home_average <- game_and_manager_data %>%
  filter((game_team == home_team & game_location == "Home" & opponent == away_team)) %>%
  summarize(h_goals = mean(goals)) %>%
  pull(h_goals)


%>%
  group_by(goals) %>%
  summarise(n_games = n_distinct(game_id)) %>%
  mutate(pct_games = n_games / sum(n_games)) %>%
  ggplot() +
  geom_point(aes(x = goals, y = pct_games), colour = "red") +
  geom_point(aes(x = goals, y = rpois(goals, game_and_manager_data %>%
  filter((game_team == home_team & game_location == "Home" & opponent == away_team)) + summarise(mean_goals = mean(goals)) %>% pull(mean_goals) )), colour = "red") 


  ggplot(aes(x = goals)) +
  geom_histogram(binwidth = 1)
  
  
get_game_score <- function(home_team, away_team) {
  selected_subset <- game_and_manager_data %>%
    filter(game_date <= as.Date('2019-01-01')) %>%
    filter((game_team == home_team & game_location == "Home" & opponent == away_team)) 
  
  n_games <- selected_subset %>% summarise(n_games = n_distinct(game_id)) %>% pull(n_games)
  
  home_average <- selected_subset %>%
  summarize(avg_goals = mean(goals)) %>%
  pull(avg_goals)
  
  away_average <- selected_subset %>%
  summarize(avg_goals = mean(opponent_goals)) %>%
  pull(avg_goals)
  
  home_goals <- rpois(1, home_average)
  away_goals <- rpois(1, away_average) 
  
  tribble(~home, ~away, ~games,
          home_goals,away_goals,n_games)
}

get_game_score("Chelsea", "Crystal Palace")

crossing(trial = 1:1000,
         home_team = "Fulham",
         away_team = "Liverpool") %>%
  mutate(result = map2(home_team, away_team, get_game_score)) %>%
  unnest() %>%
  mutate(result = if_else(home > away, home_team, if_else(home < away, away_team, "DRAW"))) %>%
  count(result) %>%
  mutate(n = n/sum(n)) %>%
  arrange(desc(n)) 
    
  

map(1:10, get_game_score("Chelsea", "Crystal Palace"))

rep(get_game_score("Bournemouth", "Newcastle"), 10)
x<-replicate(10, get_game_score("Chelsea", "Crystal Palace"))
```




```{r}
library(directlabels)

full_results %>%
  group_by(game_team) %>%
  arrange(game_date) %>%
  mutate(cumulative_points = cumsum(points)) %>%
  ggplot(aes(x = game_date, y = cumulative_points, group = game_team)) +
  geom_line() +
  geom_dl(aes(label = game_team), method = "last.points")

full_results %>%
  ggplot(aes(colour = game_location, x = points)) +
  geom_line(stat = "density")
```


# The fun bit

```{r}
full_results %<>% 
<<<<<<< HEAD
  mutate(manager_tenure = as.numeric(game_date - managed_from)) %>%
  select(-valid_date, -n) %>%
  mutate(game_location = as.factor(game_location))
=======
  mutate(manager_tenure = as.numeric(game_date - managed_from) / 7) %>%
  mutate(manager_time_remaining = as.numeric(managed_until - game_date) / 7) %>%
  select(-valid_date, -n)
>>>>>>> e5de343598463fb9afea1c32f19ea0ff77646122
```

```{r}

goals_model <- glm(goals ~ game_month + game_location, 
                   family = poisson(link = "log"), 
                   data = full_results %>% 
                     filter(! game_team %in% c('Manchester United', 'Arsenal', 'Charlton Athletic')) %>% 
                     mutate(manager_tenure = manager_tenure/365) %>%
                     mutate(game_month = as.factor(month(game_date))))

summary(goals_model)

```

```{r}
full_results %>%
  #filter(!manager_name %in% c('Alex Ferguson', 'Arsène Wenger', 'Alan Curbishley')) %>%
  mutate(weeks_remaining = floor(manager_time_remaining)) %>%
  filter(weeks_remaining <= 104) %>%
  group_by(weeks_remaining, game_location) %>%
  summarize(average_points = mean(points), ngames = n_distinct(game_id)) %>%
  ggplot(aes(x = weeks_remaining, y = average_points, color = game_location, size = ngames)) +
  geom_point(alpha = 0.7) +
  scale_x_reverse() +
  ylim(0.5,2.5) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 4), se = F) +
  geom_hline(yintercept = mean(full_results$points))

full_results %>%
  #filter(!manager_name %in% c('Alex Ferguson', 'Arsène Wenger', 'Alan Curbishley')) %>%
  mutate(weeks_tenure = floor(manager_tenure)) %>%
  filter(weeks_tenure <= 104) %>%
  group_by(weeks_tenure, game_location) %>%
  summarize(average_points = mean(points), ngames = n_distinct(game_id)) %>%
  ggplot(aes(x = weeks_tenure, y = average_points, color = game_location)) +
  geom_point(alpha = 0.7) +
  #ylim(0.5,2.5) +
  geom_smooth(method = "gam", formula = y ~ splines::ns(x, 4), se = F) +
  facet_wrap(~game_location,scales = "free") +
  geom_hline(yintercept = mean(full_results$points)) 
```

```{r}
full_results %>%
  filter(game_team == "Chelsea") %>%
  ggplot(aes(x = game_date, y = points, colour = paste(manager_name, managed_from, sep = ","))) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3), se = F)

```
```



  #filter(manager_tenure <= 8*365.25) %>%
  ggplot(aes(x = manager_time_remaining/365.25, y = jitter(points))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  facet_wrap(~game_location)

full_results %>% 
  mutate(mgr_tenure_group = cut(manager_tenure, c(0, 28, 45, 60, 90, 120, 180, 270, 365, 720, 99999))) %>%
  group_by(mgr_tenure_group, game_location, points) %>%
  tally() %>% 
  ungroup() %>%
  group_by(mgr_tenure_group, game_location) %>%
  mutate(n = n / sum(n)) %>%
  spread(points, n)

full_results %>% 
  mutate(mgr_tenure_group = cut(manager_tenure, c(-1, 28, 45, 60, 90, 120, 180, 270, 365, 720, 99999))) %>%
  group_by(mgr_tenure_group, game_location) %>%
  summarise(average_points = mean(points)) %>%
  ggplot(aes(x = mgr_tenure_group, y = average_points)) +
  geom_col() +
  facet_wrap(~ game_location)

goals <- full_result_data %>% 
  filter(valid_date) %>%
  add_count(game_id) %>% filter(n == 2) %>%
  pull(goals)

x <- MASS::fitdistr(goals, densfun = "Poisson") %>% broom::tidy()

exp_goals <- rpois(18000, lambda = x %>% pull(estimate))

curve(dpois(c(0:10), x %>% pull(estimate)))

plot(exp_goals)
```




